site_name: Dentropy's Knowledge Base
site_url: https://dentropy.github.io/
docs_dir: markdown_files
site_dir: docs
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.footer
plugins:
  - material-plausible
  - search:
      lang: en
extra:
  generator: true
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PaulWMullins
    - icon: fontawesome/solid/paper-plane
      link: mailto:dentropy@protonmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/dentropy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/paulmullins-779/
  analytics:
    provider: plausible
    domain: ddaemon.org
    src: "https://plausible.newatlantis.top/js/script.js"
nav:
- Concepts:
    - List:
        - Merkle Mountain Range?: cac99172-a808-41e3-8777-d7922961e01f
- MyProjects:
    - Verus Bridge:
        - Verus Bridge Meetings: d69ba87d-83f0-4b7a-a89d-f01c2d3d4a99
        - Verus Bridge Project Reading Backlog: cd8d2718-a1eb-4539-950f-684b49157225
        - Verus Software Interrogation: 44b40bb7-b4fa-4832-8009-ef3499e89340
- Questions:
    - list:
        - Does Solana produce a Merkle Mountain Range?: 50aa3500-f426-4a62-9178-afa6a0e002c7
        - How do Bitcoin Derived Blockchain produce a Merkle Mountain Range?: 5758461e-f94a-4f3c-8723-026650bd2882
        - How do I confirm a transaction on Solana?: 20446808-a4e9-42fe-8a7c-eb0068e8200b
        - How do I get testnet devnet solana from a faucet?: a5d6c503-943d-4153-9acf-dc4e7d3f8068
        - How do I get transaction from a specific address on Solana?: 3d3de3dd-9482-4d54-8b05-815a2e984639
        - How do I submit a transaction on Solana?: e64afeb4-4133-4fc4-89d8-8dfb76b1afe3
        - How do we reconstruct the proof of a block on Solana?: 5a960999-d05a-41cd-850d-21a44c4863f4
        - How does Ethereum produce a Merkle Mountain Range?: f6a57186-7e5b-4101-9a49-46b52f032094
        - How does Solana do Consensus?: 6754e8ab-8d9c-4061-9c84-5db2781d496e
        - How to get first principal proofs for Solana Transactions?: b0c4ccf4-e687-4892-9ec2-5329a972ca00
        - Once we get the acount proof how do we validate it for Ethereum?: 209240ed-5065-487a-8c2c-edb2c0771a15
        - Once we get the acount proof how do we validate it for Solana?: 196590bf-efb0-4489-9e23-59d649ca344f
        - Once we get the acount proof how do we validate it for Verus?: eab11dcd-4346-4810-9d30-47dc0777d0a0
        - What are the Solana Block Explorers?: 0026a883-17d3-49a7-b154-f1acbb3a2794
        - What characteristics can I use to measure and judge blockchain bridges?: 4072ce86-4060-4104-9654-32e6e7b9641b
        - What is the reference design for a Solana Bridge?: aaddae76-30e2-4f25-ae94-e0b1fd5f986e
        - What is the reference design for an EVM bridge?: f49f0475-957d-4827-a437-310bc39899b5
        - Where can I get a list of cross blockchain bridges?: f966ac69-bc19-4787-972b-60d304326cc4
- Quests:
    - List:
        - Code Audit for Veras Bridge: 7aebdd86-52ce-4a6a-a49a-22fa26e3d770
        - Deploy a Solana Token then use the Solana SDK to get all its metadata and perform transactions: 0c87e539-4f7d-4640-b527-35c46183b0ec
        - Get the Verus ID: 335bd8f1-a07c-473d-87c5-964dcd7ab005
        - Multi Signature Tutorial: d2f5cd90-9233-4cc0-b920-cc426bca101a
        - Setup a Veras Node: 294e0ee0-f6e0-4d2c-b301-ebf5ced8ba19
        - Setup the Veras Bridge: ce4736fb-f1eb-40b2-a0d2-9f9ae3fd1bdc
        - Solidity Ethereum Token Tutorial: 254ca57e-a5a6-46af-a242-98924317f551
        - Verus Bridge Project: fb7feedf-7aa9-4572-9ba5-c442f1046b7a
        - Write Solana Token Tutorial: 2f378dd9-7848-48c5-9d61-a95d25a82e27
- Software:
    - List:
        - Owl Finance Blockchain Bridge: ee402d0b-11dc-4bf9-aaf9-07ce91a3dd8f
        - Wormhole Blockchain Bridge: 506376a4-be1c-46bf-83ee-42745956a65f
- Possessions:
    - Verus Knowledge Graph Build Script: 5170ce56-1bce-40b3-b705-1fc21993212a
- Set up a Verus Blockchain Node: a7ec2fa2-1baf-470d-a07a-f220a0a854dd
- Synapse Bridge: 37016726-f3d5-4d6c-9a3e-2ae952890237
- Verus Bridge Project Important Links: ea3abca6-65dd-457e-904d-6d926f338de7
- Verus Bridge Project Logs: eccf17c8-6f7a-4e49-b944-c22d8094bca0
- Verus Bridge Project Research Dump: c3e8de10-1ecc-436b-8173-5cd1c620cfb7
- Verus Bridge Project Research Questions and Facts: e3538791-1317-4d46-b7e2-b496c23e4e5a
- Verus Bridge Project Updates: 8030d01a-970e-4c1e-866d-4e69639b1229
